language: node_js

node_js:
  - "0.10"

addons:
  firefox: "38.0"

sudo: true

env:
  global:
    - MOZ_DISABLE_NONLOCAL_CONNECTIONS=0

install:
  - cd tests
  - sudo -H pip install  ./mozbase/manifestparser
  - sudo -H pip install  ./mozbase/mozcrash
  - sudo -H pip install  ./mozbase/mozdebug
  - sudo -H pip install  ./mozbase/mozdevice
  - sudo -H pip install  ./mozbase/mozfile
  - sudo -H pip install  ./mozbase/mozhttpd
  - sudo -H pip install  ./mozbase/mozinfo
  - sudo -H pip install  ./mozbase/mozinstall
  - sudo -H pip install  ./mozbase/mozlog
  - sudo -H pip install  ./mozbase/moznetwork
  - sudo -H pip install  ./mozbase/mozprocess
  - sudo -H pip install  ./mozbase/mozprofile
  - sudo -H pip install  ./mozbase/mozrunner
  - sudo -H pip install  ./mozbase/moztest
  - sudo -H pip install  ./mozbase/mozversion
  - cd ..

script:
  - which firefox
  - ./run.sh /usr/local/bin/firefox
