language: node_js

node_js:
  - "0.10"

addons:
  firefox: "38.0"

sudo: false

env:
  global:
    - MOZ_DISABLE_NONLOCAL_CONNECTIONS=0

before_install:
  - sudo apt-get install python-virtualenv

install:
  - cd tests
  - pip install  ./mozbase/manifestparser
  - pip install  ./mozbase/mozcrash
  - pip install  ./mozbase/mozdebug
  - pip install  ./mozbase/mozdevice
  - pip install  ./mozbase/mozfile
  - pip install  ./mozbase/mozhttpd
  - pip install  ./mozbase/mozinfo
  - pip install  ./mozbase/mozinstall
  - pip install  ./mozbase/mozlog
  - pip install  ./mozbase/moznetwork
  - pip install  ./mozbase/mozprocess
  - pip install  ./mozbase/mozprofile
  - pip install  ./mozbase/mozrunner
  - pip install  ./mozbase/moztest
  - pip install  ./mozbase/mozversion

script:
  - cd tests && ./run.sh /usr/bin/firefox
